apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: slytherin-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "update", "delete"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slytherin-manage-deployments
  namespace: default
subjects:
- kind: User
  name: "malfoy"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: slytherin-deployment-manager
  apiGroup: rbac.authorization.k8s.io
